### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by Maxwelljones** [advaluti-dev/AdditionalGems#1]
Crash on startup.
Here's the logs https://pastebin.com/G2REijef

MC 1.15.2
Forge 31.2.41
![image](https://user-images.githubusercontent.com/3750700/95395531-24157200-08ff-11eb-9efc-c62e48927846.png)

**Comment by MichaelSixtyFour** [comment]
Fixed in 1.1.1 and f284757
